map $http_x_forwarded_proto $fastcgi_https {
    default off;
    https on;
}

server {
    listen 10000;
    server_name _;

    client_max_body_size 64M;

    root /var/www/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Direct static assets caching & serving (CSS/JS/images)
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS $fastcgi_https;
        fastcgi_param HTTP_HOST $host;
    }

    location ~ /\.ht {
        deny all;
    }
}